CREATE DATABASE IF NOT EXISTS snake_soccer;
USE snake_soccer;

CREATE TABLE IF NOT EXISTS tasks (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    completed BOOLEAN DEFAULT FALSE
);